sudo: required

services: 
    - docker
    
before_install:
    - docker build -t sagarmshukla/frontend -f ./client/Dockerfile.dev ./client
script:
    - docker run -e CI=true sagarmshukla/frontend npm run test -- --coverage

after_success:
    - docker build -t sagarmshukla/client ./client
    - docker build -t sagarmshukla/nginx ./nginx       
    - docker build -t sagarmshukla/server ./server 
    - docker build -t sagarmshukla/worker ./worker 

    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push sagarmshukla/client
    - docker push sagarmshukla/nginx
    - docker push sagarmshukla/server
    - docker push sagarmshukla/worker            

#deploy:
#    provider: elasticbeanstalk
#    region: "us-east-1"
#    app: "DockerWeb"
#    env: "DockerWeb-env"
#    bucket_name: "elasticbeanstalk-us-east-1-192588716298"
#    bucket_path: "docker"
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: "$AWS_KEY"
#    on:
#        branch: Master

